<script setup lang="ts">
import menuItem from './menu-item.vue';
import SWindow from './s-window.vue';

const item2 = [
  {
    versionNo: -1,
    applicationId: 'MG01000000',
    parentApplicationId: '[ROOT]',
    applicationName: '業務',
    label: '業務',
    seq: 1,
    groupTypeFg: true,
    separaterTypeFg: false,
    authorityLevel: '2',
    menuFg: true,
    applyStartDate: '20000101',
    applyEndDate: '99999999',
    children: [
      {
        versionNo: -1,
        applicationId: 'MG01001000',
        parentApplicationId: 'MG01000000',
        applicationName: '取引（注文・約定）',
        label: '取引（注文・約定）',
        seq: 1,
        groupTypeFg: true,
        separaterTypeFg: false,
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
        children: [
          {
            versionNo: -1,
            applicationId: 'MG01001002',
            parentApplicationId: 'MG01001000',
            applicationName: '外国株式等',
            label: '外国株式等',
            seq: 2,
            groupTypeFg: true,
            separaterTypeFg: false,
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
            children: [
              {
                versionNo: -1,
                applicationId: 'CW81000010',
                parentApplicationId: 'MG01001002',
                applicationName: '外国株式等買付注文',
                label: '外国株式等買付注文',
                seq: 1,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '05',
                moduleId2: 'SbiForeignStockBuyOrder',
                serviceId: 'sbiForeignStockOrderService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW8100002S',
                parentApplicationId: 'MG01001002',
                applicationName: '外国株式等売却注文',
                label: '外国株式等売却注文',
                seq: 2,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '05',
                moduleId2: 'SbiForeignStockSellOrder',
                serviceId: 'sbiForeignStockOrderService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW81000110',
                parentApplicationId: 'MG01001002',
                applicationName: '外国株式等注文一覧',
                label: '外国株式等注文一覧',
                seq: 3,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '03',
                moduleId1: 'SbiForeignStockOrderList',
                serviceId: 'sbiForeignStockOrderService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW8100012S',
                parentApplicationId: 'MG01001002',
                applicationName: '外国株式プール注文一覧',
                label: '外国株式プール注文一覧',
                seq: 5,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '02',
                moduleId1: 'SbiForeignStockOrderList4Pool',
                serviceId: 'sbiForeignStockOrderService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW81000221',
                parentApplicationId: 'MG01001002',
                applicationName: '外国株式等信用新規建注文',
                label: '外国株式等信用新規建注文',
                seq: 5,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '05',
                moduleId2: 'SbiForeignStockMarginOpenOrderRegister',
                serviceId: 'sbiForeignStockMarginOrderService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20200101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW81000222',
                parentApplicationId: 'MG01001002',
                applicationName: '外国株式等信用決済注文',
                label: '外国株式等信用決済注文',
                seq: 7,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '01',
                moduleId1: 'SbiForeignStockMarginCloseOrderSearch',
                moduleId2: 'SbiForeignStockMarginCloseOrderForm',
                serviceId: 'sbiForeignStockMarginOrderService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20200101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW81000200',
                parentApplicationId: 'MG01001002',
                applicationName: '外国株式等信用注文一覧',
                label: '外国株式等信用注文一覧',
                seq: 8,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '03',
                moduleId1: 'SbiForeignStockMarginOrderSearch',
                serviceId: 'sbiForeignStockMarginOrderService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20200101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW81000223',
                parentApplicationId: 'MG01001002',
                applicationName: '外国株式等信用建玉強制決済指示',
                label: '外国株式等信用建玉強制決済指示',
                seq: 12,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '10',
                moduleId1: 'SbiForeignStockMandatoryClosingList',
                serviceId: 'sbiCollateralService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20200101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW81000220',
                parentApplicationId: 'MG01001002',
                applicationName: '外国株式等信用強制決済注文照会',
                label: '外国株式等信用強制決済注文照会',
                seq: 13,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '03',
                moduleId1: 'SbiForeignStockMandCloseInqueryList',
                serviceId: 'sbiForeignStockMarginOrderService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20200101',
                applyEndDate: '99999999',
              },
            ],
          },
          {
            versionNo: -1,
            applicationId: 'MG01001003',
            parentApplicationId: 'MG01001000',
            applicationName: '外国債券',
            label: '外国債券',
            seq: 3,
            groupTypeFg: true,
            separaterTypeFg: false,
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
            children: [
              {
                versionNo: -1,
                applicationId: 'CW8200001S',
                parentApplicationId: 'MG01001003',
                applicationName: '外国債券買付注文',
                label: '外国債券買付注文',
                seq: 1,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '05',
                moduleId2: 'SbiForeignBondBuyOrder',
                serviceId: 'sbiForeignBondOutsideOrderService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW8200002S',
                parentApplicationId: 'MG01001003',
                applicationName: '外国債券売却注文',
                label: '外国債券売却注文',
                seq: 2,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '05',
                moduleId2: 'SbiFBondSellOrder',
                serviceId: 'sbiFBondOutsideOrderService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW82000110',
                parentApplicationId: 'MG01001003',
                applicationName: '外国債券注文一覧',
                label: '外国債券注文一覧',
                seq: 3,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '03',
                moduleId1: 'ForeignBondOrderList',
                serviceId: 'foreignBondOutsideOrderService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
            ],
          },
          {
            versionNo: -1,
            applicationId: 'MG01001007',
            parentApplicationId: 'MG01001000',
            applicationName: '外貨建ＭＭＦ',
            label: '外貨建ＭＭＦ',
            seq: 7,
            groupTypeFg: true,
            separaterTypeFg: false,
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
            children: [
              {
                versionNo: -1,
                applicationId: 'CW89000010',
                parentApplicationId: 'MG01001007',
                applicationName: '外貨建ＭＭＦ買付注文',
                label: '外貨建ＭＭＦ買付注文',
                seq: 1,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '05',
                moduleId2: 'ForeignFundDlyBuyOrder',
                serviceId: 'foreignFundDailyOrderService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW8900002S',
                parentApplicationId: 'MG01001007',
                applicationName: '外貨建ＭＭＦ売却注文',
                label: '外貨建ＭＭＦ売却注文',
                seq: 2,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '05',
                moduleId2: 'SbiFFundDlySellOrder',
                serviceId: 'sbiFFundDailyOrderService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW89000110',
                parentApplicationId: 'MG01001007',
                applicationName: '外貨建ＭＭＦ注文一覧',
                label: '外貨建ＭＭＦ注文一覧',
                seq: 3,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '03',
                moduleId1: 'ForeignFundDailyOrderList',
                serviceId: 'foreignFundDailyOrderService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
            ],
          },
        ],
      },
      {
        versionNo: -1,
        applicationId: 'MG01002000',
        parentApplicationId: 'MG01000000',
        applicationName: '注文・出来・失効管理',
        label: '注文・出来・失効管理',
        seq: 2,
        groupTypeFg: true,
        separaterTypeFg: false,
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
        children: [
          {
            versionNo: -1,
            applicationId: 'MG01002002',
            parentApplicationId: 'MG01002000',
            applicationName: '外国株式等',
            label: '外国株式等',
            seq: 2,
            groupTypeFg: true,
            separaterTypeFg: false,
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
            children: [
              {
                versionNo: -1,
                applicationId: 'CW81000120',
                parentApplicationId: 'MG01002002',
                applicationName: '外国株式等注文管理',
                label: '外国株式等注文管理',
                seq: 1,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '03',
                moduleId1: 'ForeignStockOrderManagement',
                serviceId: 'foreignStockOrderService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW8100020S',
                parentApplicationId: 'MG01002002',
                applicationName: '現地精算金額集計情報',
                label: '現地精算金額集計情報',
                seq: 2,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '07',
                moduleId1: 'SbiForeignStockOrderAmount',
                serviceId: 'sbiForeignStockOrderAmountService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW8100030S',
                parentApplicationId: 'MG01002002',
                applicationName: '差金決済抑止取引制限管理',
                label: '差金決済抑止取引制限管理',
                seq: 3,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '01',
                moduleId1: 'SettlementRestrictManagementSearch',
                moduleId2: 'SettlementRestrictManagementForm',
                serviceId: 'settlementRestrictService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
            ],
          },
          {
            versionNo: -1,
            applicationId: 'MG01002003',
            parentApplicationId: 'MG01002000',
            applicationName: '外国債券',
            label: '外国債券',
            seq: 3,
            groupTypeFg: true,
            separaterTypeFg: false,
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
            children: [
              {
                versionNo: -1,
                applicationId: 'CW82500030',
                parentApplicationId: 'MG01002003',
                applicationName: '外国債券販売枠管理',
                label: '外国債券販売枠管理',
                seq: 1,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '01',
                moduleId1: 'ForeignBondSalesAmountSearch',
                moduleId2: 'ForeignBondSalesAmountForm',
                serviceId: 'foreignBondSalesAmountService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW8250002S',
                parentApplicationId: 'MG01002003',
                applicationName: '外国債券販売枠管理（ネットチャンネル専用）',
                label: '外国債券販売枠管理（ネットチャンネル専用）',
                seq: 2,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '01',
                moduleId1: 'SbiForeignBondNetSalesAmountSearch',
                moduleId2: 'SbiForeignBondNetSalesAmountForm',
                serviceId: 'sbiForeignBondNetSalesAmountService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
            ],
          },
          {
            versionNo: -1,
            applicationId: 'CW00000010',
            parentApplicationId: 'MG01002000',
            applicationName: '注文･出来情報照会',
            label: '注文･出来情報照会',
            seq: 4,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '02',
            moduleId1: 'OrderExecutionInfoSearch',
            serviceId: 'orderExecutionInfoService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
        ],
      },
      {
        versionNo: -1,
        applicationId: 'MG01003000',
        parentApplicationId: 'MG01000000',
        applicationName: '発注管理',
        label: '発注管理',
        seq: 3,
        groupTypeFg: true,
        separaterTypeFg: false,
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
        children: [
          {
            versionNo: -1,
            applicationId: 'CW00900300',
            parentApplicationId: 'MG01003000',
            applicationName: '市場商品発注状況一覧',
            label: '市場商品発注状況一覧',
            seq: 1,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'SbiPlaceOrderStatusSearch',
            moduleId2: 'SbiPlaceOrderStatusForm',
            serviceId: 'placeOrderStatusService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00900310',
            parentApplicationId: 'MG01003000',
            applicationName: '市場外商品発注状況一覧',
            label: '市場外商品発注状況一覧',
            seq: 2,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'OutsideOrderStatusSearch',
            moduleId2: 'OutsideOrderStatusForm',
            serviceId: 'outsideOrderStatusService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
        ],
      },
      {
        versionNo: -1,
        applicationId: 'MG01004000',
        parentApplicationId: 'MG01000000',
        applicationName: '入出金・入出庫管理',
        label: '入出金・入出庫管理',
        seq: 4,
        groupTypeFg: true,
        separaterTypeFg: false,
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
        children: [
          {
            versionNo: -1,
            applicationId: 'MG01004001',
            parentApplicationId: 'MG01004000',
            applicationName: '入出金管理',
            label: '入出金管理',
            seq: 1,
            groupTypeFg: true,
            separaterTypeFg: false,
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
            children: [
              {
                versionNo: -1,
                applicationId: 'CW00010010',
                parentApplicationId: 'MG01004001',
                applicationName: '入出金管理',
                label: '入出金管理',
                seq: 1,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '10',
                moduleId1: 'ClientMoneyEntryManagement',
                serviceId: 'clientMoneyEntryService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW00010020',
                parentApplicationId: 'MG01004001',
                applicationName: '入出金入力',
                label: '入出金入力',
                seq: 2,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '09',
                moduleId1: 'ClientMoneyEntrySearch',
                moduleId2: 'ClientMoneyEntryForm',
                serviceId: 'clientMoneyEntryService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
            ],
          },
        ],
      },
      {
        versionNo: -1,
        applicationId: 'MG01005000',
        parentApplicationId: 'MG01000000',
        applicationName: '余力管理・残高管理',
        label: '余力管理・残高管理',
        seq: 5,
        groupTypeFg: true,
        separaterTypeFg: false,
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
        children: [
          {
            versionNo: -1,
            applicationId: 'CW00020010',
            parentApplicationId: 'MG01005000',
            applicationName: '買付・出金可能金額照会',
            label: '買付・出金可能金額照会',
            seq: 1,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '04',
            moduleId1: 'CustCashScheduleForWebSearch',
            serviceId: 'balanceService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00020030',
            parentApplicationId: 'MG01005000',
            applicationName: '証券残高一覧照会',
            label: '証券残高一覧照会',
            seq: 3,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '02',
            moduleId1: 'CustSecBalanceListSearch',
            serviceId: 'balanceService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00020040',
            parentApplicationId: 'MG01005000',
            applicationName: '取引履歴一覧照会',
            label: '取引履歴一覧照会',
            seq: 4,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '07',
            moduleId1: 'TradeRecordList',
            serviceId: 'tradeRecordService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00020060',
            parentApplicationId: 'MG01005000',
            applicationName: '金銭余力拘束付与入力',
            label: '金銭余力拘束付与入力',
            seq: 5,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '09',
            moduleId1: 'RemainingPower4FixedAmountSearch',
            moduleId2: 'RemainingPower4FixedAmountForm',
            serviceId: 'balanceService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00020050',
            parentApplicationId: 'MG01005000',
            applicationName: '金銭余力拘束付与一覧',
            label: '金銭余力拘束付与一覧',
            seq: 6,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '02',
            moduleId1: 'RemainingPower4FixedAmountList',
            serviceId: 'balanceService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00020070',
            parentApplicationId: 'MG01005000',
            applicationName: 'NISA口座残高振替入力',
            label: 'NISA口座残高振替入力',
            seq: 8,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '09',
            moduleId1: 'BalanceTransferInputSearch',
            moduleId2: 'BalanceTransferInputForm',
            serviceId: 'balanceTransferService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20131101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00020080',
            parentApplicationId: 'MG01005000',
            applicationName: 'NISA口座残高振替管理',
            label: 'NISA口座残高振替管理',
            seq: 9,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '10',
            moduleId1: 'BalanceTransferManagedSearch',
            serviceId: 'balanceTransferService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20131101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00020170',
            parentApplicationId: 'MG01005000',
            applicationName: '特定口座残高振替入力',
            label: '特定口座残高振替入力',
            seq: 10,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '09',
            moduleId1: 'BalanceTransferSpecificInputSearch',
            moduleId2: 'BalanceTransferSpecificInputForm',
            serviceId: 'balanceTransferService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00020180',
            parentApplicationId: 'MG01005000',
            applicationName: '特定口座残高振替管理',
            label: '特定口座残高振替管理',
            seq: 11,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '10',
            moduleId1: 'BalanceTransferSpecificManagedSearch',
            serviceId: 'balanceTransferService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00200010',
            parentApplicationId: 'MG01005000',
            applicationName: '金銭残高振替照会',
            label: '金銭残高振替照会',
            seq: 12,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '10',
            moduleId1: 'SbiCollateralList',
            serviceId: 'collateralService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20200101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00200011',
            parentApplicationId: 'MG01005000',
            applicationName: '金銭残高振替入力',
            label: '金銭残高振替入力',
            seq: 13,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '09',
            moduleId1: 'SbiCollateralSearch',
            moduleId2: 'SbiCollateralForm',
            serviceId: 'sbiCollateralService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20200101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00200020',
            parentApplicationId: 'MG01005000',
            applicationName: '残高預り区分変更管理',
            label: '残高預り区分変更管理',
            seq: 14,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '03',
            moduleId1: 'SbiSubDepositTransferInfoList',
            serviceId: 'subDepositTransferInfoService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20200101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00200021',
            parentApplicationId: 'MG01005000',
            applicationName: '残高預り区分変更指示',
            label: '残高預り区分変更指示',
            seq: 15,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '09',
            moduleId1: 'SbiSubDepositTransferInfoSearch',
            moduleId2: 'SbiSubDepositTransferInfoForm',
            serviceId: 'sbiCollateralService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20200101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00500200',
            parentApplicationId: 'MG01005000',
            applicationName: '信用建余力照会',
            label: '信用建余力照会',
            seq: 16,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '07',
            moduleId1: 'SbiMarginBuyingPowerList',
            serviceId: 'sbiMarginBuyingPowerService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20200101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW81000204',
            parentApplicationId: 'MG01005000',
            applicationName: '外国株式等信用建玉照会',
            label: '外国株式等信用建玉照会',
            seq: 17,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '03',
            moduleId1: 'SbiForeignStockPositionSearch',
            serviceId: 'sbiForeignStockPositionService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20200101',
            applyEndDate: '99999999',
          },
        ],
      },
      {
        versionNo: -1,
        applicationId: 'MG01006000',
        parentApplicationId: 'MG01000000',
        applicationName: '外国為替管理',
        label: '外国為替管理',
        seq: 6,
        groupTypeFg: true,
        separaterTypeFg: false,
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
        children: [
          {
            versionNo: -1,
            applicationId: 'CW00500230',
            parentApplicationId: 'MG01006000',
            applicationName: '外国為替情報',
            label: '外国為替情報',
            seq: 1,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '11',
            moduleId1: 'ExchangeRateInfoSearch',
            moduleId2: 'ExchangeRateInfoForm',
            serviceId: 'exchangeRateInfoService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
        ],
      },
      {
        versionNo: -1,
        applicationId: 'MG01007000',
        parentApplicationId: 'MG01000000',
        applicationName: '口座管理',
        label: '口座管理',
        seq: 7,
        groupTypeFg: true,
        separaterTypeFg: false,
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
        children: [
          {
            versionNo: -1,
            applicationId: 'CW0050001S',
            parentApplicationId: 'MG01007000',
            applicationName: '個人顧客口座管理',
            label: '個人顧客口座管理',
            seq: 1,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '98',
            moduleId1: 'AccountInfoIndividualSearch',
            moduleId2: 'SbiAccountInfoIndividualForm',
            serviceId: 'sbiAccountIndividualService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00500020',
            parentApplicationId: 'MG01007000',
            applicationName: '法人顧客口座管理',
            label: '法人顧客口座管理',
            seq: 2,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '98',
            moduleId1: 'AccountInfoCorporateSearch',
            moduleId2: 'AccountInfoCorporateForm',
            serviceId: 'sbiAccountCorporateService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20200101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW0050003S',
            parentApplicationId: 'MG01007000',
            applicationName: '口座情報検索',
            label: '口座情報検索',
            seq: 3,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '02',
            moduleId1: 'SbiAccountInfoSearch',
            serviceId: 'accountService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00500040',
            parentApplicationId: 'MG01007000',
            applicationName: '顧客取引制限管理',
            label: '顧客取引制限管理',
            seq: 4,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'AccountTradeRestrictSearch',
            moduleId2: 'AccountTradeRestrictForm',
            serviceId: 'accountTradeRestrictService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00500210',
            parentApplicationId: 'MG01007000',
            applicationName: 'BM送信除外顧客管理',
            label: 'BM送信除外顧客管理',
            seq: 5,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'SbiAccountBmExcludeSearch',
            moduleId2: 'SbiAccountBmExcludeForm',
            serviceId: 'accountBmExcludeService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20200101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00500080',
            parentApplicationId: 'MG01007000',
            applicationName: 'NISA移動・損益明細照会',
            label: 'NISA移動・損益明細照会',
            seq: 8,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '07',
            moduleId1: 'SbiNisaMovingPL',
            serviceId: 'sbiNisaMovingPLService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20131101',
            applyEndDate: '20230926',
          },
          {
            versionNo: -1,
            applicationId: 'CW00500050',
            parentApplicationId: 'MG01007000',
            applicationName: '外貨振込先金融機関口座管理',
            label: '外貨振込先金融機関口座管理',
            seq: 9,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '16',
            moduleId1: 'SbiAccountSearch',
            moduleId2: 'SbiAccountForm',
            serviceId: 'sbiAccountService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'MG01007010',
            parentApplicationId: 'MG01007000',
            applicationName: '外国株式信用取引',
            label: '外国株式信用取引',
            seq: 9,
            groupTypeFg: true,
            separaterTypeFg: false,
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20200101',
            applyEndDate: '99999999',
            children: [
              {
                versionNo: -1,
                applicationId: 'CW00581201',
                parentApplicationId: 'MG01007010',
                applicationName: '口座銘柄別掛目',
                label: '口座銘柄別掛目',
                seq: 1,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '01',
                moduleId1: 'SbiAccountSecuritiesCollateralSetSearch',
                moduleId2: 'SbiAccountSecuritiesCollateralSetForm',
                serviceId: 'accountSecuritiesCollateralSetService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20200101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW00581202',
                parentApplicationId: 'MG01007010',
                applicationName: '口座銘柄別建玉限度額',
                label: '口座銘柄別建玉限度額',
                seq: 2,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '01',
                moduleId1: 'SbiAccountSecuritiesPositionSearch',
                moduleId2: 'SbiAccountSecuritiesPositionForm',
                serviceId: 'accountSecuritiesPositionService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20200101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW00500202',
                parentApplicationId: 'MG01007010',
                applicationName: '口座別建玉限度額',
                label: '口座別建玉限度額',
                seq: 3,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '01',
                moduleId1: 'SbiAccountPositionSearch',
                moduleId2: 'SbiAccountPositionForm',
                serviceId: 'accountPositionService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20200101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW00500201',
                parentApplicationId: 'MG01007010',
                applicationName: '追証解除設定',
                label: '追証解除設定',
                seq: 4,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '05',
                moduleId2: 'MarginCallSetting',
                serviceId: 'sbiMarginCallService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20200101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW00500203',
                parentApplicationId: 'MG01007010',
                applicationName: '顧客別デフォルト設定',
                label: '顧客別デフォルト設定',
                seq: 7,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '05',
                moduleId2: 'SbiAccountMarginDefaultSetting',
                serviceId: 'collateralService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20200101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW00500204',
                parentApplicationId: 'MG01007010',
                applicationName: '顧客別預り金不足管理',
                label: '顧客別預り金不足管理',
                seq: 8,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '16',
                moduleId1: 'SbiDeficitCashBalanceSearch',
                moduleId2: 'SbiDeficitCashBalanceForm',
                serviceId: 'deficitCashBalanceService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20200101',
                applyEndDate: '99999999',
              },
            ],
          },
        ],
      },
      {
        versionNo: -1,
        applicationId: 'MG01009000',
        parentApplicationId: 'MG01000000',
        applicationName: '銘柄管理',
        label: '銘柄管理',
        seq: 9,
        groupTypeFg: true,
        separaterTypeFg: false,
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
        children: [
          {
            versionNo: -1,
            applicationId: 'MG01009001',
            parentApplicationId: 'MG01009000',
            applicationName: '株式銘柄',
            label: '株式銘柄',
            seq: 1,
            groupTypeFg: true,
            separaterTypeFg: false,
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
            children: [
              {
                versionNo: -1,
                applicationId: 'CW8150001S',
                parentApplicationId: 'MG01009001',
                applicationName: '外国株式等銘柄情報',
                label: '外国株式等銘柄情報',
                seq: 2,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '01',
                moduleId1: 'ForeignStockInfoSearch',
                moduleId2: 'SbiForeignStockInfoForm',
                serviceId: 'foreignStockInfoService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW81500040',
                parentApplicationId: 'MG01009001',
                applicationName: '外国株式権利付売買最終日情報',
                label: '外国株式権利付売買最終日情報',
                seq: 2,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '07',
                moduleId1: 'ForeignRightScheduleServiceSearch',
                serviceId: 'foreignRightScheduleService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW81500203',
                parentApplicationId: 'MG01009001',
                applicationName: '外国株式等銘柄マスタ更新履歴一覧',
                label: '外国株式等銘柄マスタ更新履歴一覧',
                seq: 2,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '03',
                moduleId1: 'SbiForeignStockSecuritiesList',
                serviceId: 'foreignStockInfoService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20200101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW8150003S',
                parentApplicationId: 'MG01009001',
                applicationName: '外国株式個社別設定売買停止銘柄一覧',
                label: '外国株式個社別設定売買停止銘柄一覧',
                seq: 3,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '07',
                moduleId1: 'SbiForeignStockInfo4TradingStop',
                serviceId: 'sbiForeignStockInfoService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW81500200',
                parentApplicationId: 'MG01009001',
                applicationName: '外国株式等信用取扱銘柄一覧',
                label: '外国株式等信用取扱銘柄一覧',
                seq: 4,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '03',
                moduleId1: 'SbiMarginSecuritiesInfoHandlingList',
                serviceId: 'marginSecuritiesInfoHandlingService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20200101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW81500201',
                parentApplicationId: 'MG01009001',
                applicationName: '外国株式等信用取扱銘柄情報',
                label: '外国株式等信用取扱銘柄情報',
                seq: 5,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '11',
                moduleId1: 'SbiMarginSecuritiesInfoHandlingSearch',
                moduleId2: 'SbiMarginSecuritiesInfoHandlingForm',
                serviceId: 'marginSecuritiesInfoHandlingService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20200101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW81500202',
                parentApplicationId: 'MG01009001',
                applicationName: '外国株式等総合NISA対象銘柄一覧',
                label: '外国株式等総合NISA対象銘柄一覧',
                seq: 6,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '03',
                moduleId1: 'SbiGeneralNisaSecuritiesInfoList',
                serviceId: 'sbiGeneralNisaSecuritiesInfoService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
            ],
          },
          {
            versionNo: -1,
            applicationId: 'MG01009002',
            parentApplicationId: 'MG01009000',
            applicationName: '債券銘柄',
            label: '債券銘柄',
            seq: 2,
            groupTypeFg: true,
            separaterTypeFg: false,
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
            children: [
              {
                versionNo: -1,
                applicationId: 'CW82500010',
                parentApplicationId: 'MG01009002',
                applicationName: '外国債券銘柄情報',
                label: '外国債券銘柄情報',
                seq: 2,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '01',
                moduleId1: 'ForeignBondInfoSearch',
                moduleId2: 'ForeignBondInfoForm',
                serviceId: 'foreignBondInfoService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW82500040',
                parentApplicationId: 'MG01009002',
                applicationName: '外国債券経過利子計算方式情報',
                label: '外国債券経過利子計算方式情報',
                seq: 3,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '01',
                moduleId1: 'BondCalculationBaseSearch',
                moduleId2: 'BondCalculationBaseForm',
                serviceId: 'bondCalculationBaseService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
            ],
          },
          {
            versionNo: -1,
            applicationId: 'MG01009003',
            parentApplicationId: 'MG01009000',
            applicationName: '投信銘柄',
            label: '投信銘柄',
            seq: 3,
            groupTypeFg: true,
            separaterTypeFg: false,
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
            children: [
              {
                versionNo: -1,
                applicationId: 'CW89500010',
                parentApplicationId: 'MG01009003',
                applicationName: '外貨建ＭＭＦ銘柄情報',
                label: '外貨建ＭＭＦ銘柄情報',
                seq: 4,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '01',
                moduleId1: 'ForeignFundDailyInfoSearch',
                moduleId2: 'ForeignFundDailyInfoForm',
                serviceId: 'foreignFundDailyInfoService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
            ],
          },
          {
            versionNo: -1,
            applicationId: 'MG01009004',
            parentApplicationId: 'MG01009000',
            applicationName: '呼値管理',
            label: '呼値管理',
            seq: 4,
            groupTypeFg: true,
            separaterTypeFg: false,
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
            children: [
              {
                versionNo: -1,
                applicationId: 'CW00500100',
                parentApplicationId: 'MG01009004',
                applicationName: '呼値情報',
                label: '呼値情報',
                seq: 1,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '01',
                moduleId1: 'TickDenomiInfoSearch',
                moduleId2: 'TickDenomiInfoForm',
                serviceId: 'tickDenomiService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
            ],
          },
          {
            versionNo: -1,
            applicationId: 'MG01009005',
            parentApplicationId: 'MG01009000',
            applicationName: '制限値幅管理',
            label: '制限値幅管理',
            seq: 5,
            groupTypeFg: true,
            separaterTypeFg: false,
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
            children: [
              {
                versionNo: -1,
                applicationId: 'CW00500110',
                parentApplicationId: 'MG01009005',
                applicationName: '制限値幅情報',
                label: '制限値幅情報',
                seq: 1,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '01',
                moduleId1: 'PriceRangeInfoSearch',
                moduleId2: 'PriceRangeInfoForm',
                serviceId: 'priceRangeService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
            ],
          },
        ],
      },
      {
        versionNo: -1,
        applicationId: 'MG01010000',
        parentApplicationId: 'MG01000000',
        applicationName: '時価情報管理',
        label: '時価情報管理',
        seq: 10,
        groupTypeFg: true,
        separaterTypeFg: false,
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
        children: [
          {
            versionNo: -1,
            applicationId: 'MG01010001',
            parentApplicationId: 'MG01010000',
            applicationName: '株式時価',
            label: '株式時価',
            seq: 1,
            groupTypeFg: true,
            separaterTypeFg: false,
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
            children: [
              {
                versionNo: -1,
                applicationId: 'CW81500020',
                parentApplicationId: 'MG01010001',
                applicationName: '外国株式等時価情報',
                label: '外国株式等時価情報',
                seq: 2,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '11',
                moduleId1: 'ForeignStockBasePriceSearch',
                moduleId2: 'ForeignStockBasePriceForm',
                serviceId: 'foreignStockBasePriceService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
            ],
          },
          {
            versionNo: -1,
            applicationId: 'MG01010002',
            parentApplicationId: 'MG01010000',
            applicationName: '債券時価',
            label: '債券時価',
            seq: 2,
            groupTypeFg: true,
            separaterTypeFg: false,
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
            children: [
              {
                versionNo: -1,
                applicationId: 'CW82500020',
                parentApplicationId: 'MG01010002',
                applicationName: '外国債券時価情報',
                label: '外国債券時価情報',
                seq: 2,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '11',
                moduleId1: 'ForeignBondBasePriceSearch',
                moduleId2: 'ForeignBondBasePriceForm',
                serviceId: 'foreignBondBasePriceService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
            ],
          },
          {
            versionNo: -1,
            applicationId: 'MG01010003',
            parentApplicationId: 'MG01010000',
            applicationName: '投信基準価額',
            label: '投信基準価額',
            seq: 3,
            groupTypeFg: true,
            separaterTypeFg: false,
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
            children: [
              {
                versionNo: -1,
                applicationId: 'CW89500020',
                parentApplicationId: 'MG01010003',
                applicationName: '外貨建ＭＭＦ基準価額情報',
                label: '外貨建ＭＭＦ基準価額情報',
                seq: 4,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '11',
                moduleId1: 'ForeignFundDailyBasePriceSearch',
                moduleId2: 'ForeignFundDailyBasePriceForm',
                serviceId: 'foreignFundDailyBasePriceService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
            ],
          },
        ],
      },
      {
        versionNo: -1,
        applicationId: 'MG01011000',
        parentApplicationId: 'MG01000000',
        applicationName: 'FIXシミュレーター',
        label: 'FIXシミュレーター',
        seq: 10,
        groupTypeFg: true,
        separaterTypeFg: false,
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20200101',
        applyEndDate: '99999999',
        children: [
          {
            versionNo: -1,
            applicationId: 'CW8100901S',
            parentApplicationId: 'MG01011000',
            applicationName: 'FIXシミュレーター注文管理',
            label: 'FIXシミュレーター注文管理',
            seq: 1,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '03',
            moduleId1: 'SbiFixSimulatorList',
            serviceId: 'sbiFixSimulatorService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20200101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW8100902S',
            parentApplicationId: 'MG01011000',
            applicationName: 'FIX電文情報入力',
            label: 'FIX電文情報入力',
            seq: 2,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '05',
            moduleId2: 'FixSimulatorReg',
            serviceId: 'fixSimulatorRegService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20200101',
            applyEndDate: '99999999',
          },
        ],
      },
    ],
  },
  {
    versionNo: -1,
    applicationId: 'MG02000000',
    parentApplicationId: '[ROOT]',
    applicationName: 'システム管理',
    label: 'システム管理',
    seq: 2,
    groupTypeFg: true,
    separaterTypeFg: false,
    authorityLevel: '2',
    menuFg: true,
    applyStartDate: '20000101',
    applyEndDate: '99999999',
    children: [
      {
        versionNo: -1,
        applicationId: 'MG02001000',
        parentApplicationId: 'MG02000000',
        applicationName: '組織管理',
        label: '組織管理',
        seq: 1,
        groupTypeFg: true,
        separaterTypeFg: false,
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
        children: [
          {
            versionNo: -1,
            applicationId: 'CW00500180',
            parentApplicationId: 'MG02001000',
            applicationName: '利用者管理',
            label: '利用者管理',
            seq: 1,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'UserInfoSearch',
            moduleId2: 'UserInfoForm',
            serviceId: 'usersService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00500160',
            parentApplicationId: 'MG02001000',
            applicationName: '部店管理',
            label: '部店管理',
            seq: 2,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'BranchInfoSearch',
            moduleId2: 'BranchInfoForm',
            serviceId: 'branchService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00500190',
            parentApplicationId: 'MG02001000',
            applicationName: '利用者グループ管理',
            label: '利用者グループ管理',
            seq: 3,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'UsersGroupInfoSearch',
            moduleId2: 'UsersGroupInfoForm',
            serviceId: 'userGroupService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00500170',
            parentApplicationId: 'MG02001000',
            applicationName: '部店グループ管理',
            label: '部店グループ管理',
            seq: 4,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'BranchGroupInfoSearch',
            moduleId2: 'BranchGroupInfoForm',
            serviceId: 'branchGroupService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW0050018S',
            parentApplicationId: 'MG02001000',
            applicationName: '仲介業利用者管理',
            label: '仲介業利用者管理',
            seq: 5,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'SbiUserInfoSearch',
            moduleId2: 'SbiUserInfoForm',
            serviceId: 'sbiUsersService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
        ],
      },
      {
        versionNo: -1,
        applicationId: 'MG02002000',
        parentApplicationId: 'MG02000000',
        applicationName: '手数料管理',
        label: '手数料管理',
        seq: 2,
        groupTypeFg: true,
        separaterTypeFg: false,
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
        children: [
          {
            versionNo: -1,
            applicationId: 'CW00510010',
            parentApplicationId: 'MG02002000',
            applicationName: '手数料管理',
            label: '手数料管理',
            seq: 1,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'CommissionSearch',
            moduleId2: 'SbiCommissionForm',
            serviceId: 'commissionService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00510020',
            parentApplicationId: 'MG02002000',
            applicationName: '手数料グループ登録',
            label: '手数料グループ登録',
            seq: 2,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'CommissionGroupSearch',
            moduleId2: 'CommissionGroupForm',
            serviceId: 'commissionGroupService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00510030',
            parentApplicationId: 'MG02002000',
            applicationName: '手数料グループ口座登録',
            label: '手数料グループ口座登録',
            seq: 3,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'CommissionGroupMembersSearch',
            moduleId2: 'CommissionGroupMembersForm',
            serviceId: 'commissionGroupMembersService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00510070',
            parentApplicationId: 'MG02002000',
            applicationName: '手数料グループ口座一覧',
            label: '手数料グループ口座一覧',
            seq: 4,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '07',
            moduleId1: 'CommissionGroupMembersList',
            serviceId: 'commissionGroupMembersListService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00510040',
            parentApplicationId: 'MG02002000',
            applicationName: '投信手数料管理',
            label: '投信手数料管理',
            seq: 5,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'FundCommissionSearch',
            moduleId2: 'FundCommissionForm',
            serviceId: 'fundCommissionService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00510050',
            parentApplicationId: 'MG02002000',
            applicationName: 'ランク別手数料管理',
            label: 'ランク別手数料管理',
            seq: 6,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'RankCommissionSearch',
            moduleId2: 'RankCommissionForm',
            serviceId: 'rankCommissionService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW0051013S',
            parentApplicationId: 'MG02002000',
            applicationName: '手数料グループ口座登録（扱者別）',
            label: '手数料グループ口座登録（扱者別）',
            seq: 7,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'SbiCommissionGroupMembers4SalesSearch',
            moduleId2: 'SbiCommissionGroupMembers4SalesForm',
            serviceId: 'sbiComGroupMembers4SalesService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW0051023S',
            parentApplicationId: 'MG02002000',
            applicationName: '手数料グループ口座登録（部店別）',
            label: '手数料グループ口座登録（部店別）',
            seq: 8,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'SbiCommissionGroupMembers4BranchSearch',
            moduleId2: 'SbiCommissionGroupMembers4BranchForm',
            serviceId: 'sbiComGroupMembers4BranchService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
        ],
      },
      {
        versionNo: -1,
        applicationId: 'MG02003000',
        parentApplicationId: 'MG02000000',
        applicationName: '日付管理',
        label: '日付管理',
        seq: 3,
        groupTypeFg: true,
        separaterTypeFg: false,
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
        children: [
          {
            versionNo: -1,
            applicationId: 'CW00900010',
            parentApplicationId: 'MG02003000',
            applicationName: '営業日・暦日情報',
            label: '営業日・暦日情報',
            seq: 1,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '07',
            moduleId1: 'CalendarDateRef',
            serviceId: 'calendarDateRefService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00900020',
            parentApplicationId: 'MG02003000',
            applicationName: '基準日情報',
            label: '基準日情報',
            seq: 2,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'SecBaseDateSearch',
            moduleId2: 'SecBaseDateForm',
            serviceId: 'secBaseDateService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00900040',
            parentApplicationId: 'MG02003000',
            applicationName: '国別カレンダー情報',
            label: '国別カレンダー情報',
            seq: 4,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '06',
            moduleId1: 'CalendarSearch',
            moduleId2: 'CalendarForm',
            serviceId: 'calendarService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00900050',
            parentApplicationId: 'MG02003000',
            applicationName: 'ファンドカレンダー情報',
            label: 'ファンドカレンダー情報',
            seq: 5,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '06',
            moduleId1: 'CalendarSearch',
            moduleId2: 'CalendarForm',
            serviceId: 'calendarFundService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00900011',
            parentApplicationId: 'MG02003000',
            applicationName: 'ファンドカレンダー基本情報',
            label: 'ファンドカレンダー基本情報',
            seq: 6,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'FundCalendarInfoSearch',
            moduleId2: 'FundCalendarInfoForm',
            serviceId: 'fundCalendarInfoService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW0090006S',
            parentApplicationId: 'MG02003000',
            applicationName: '現地約定日検索',
            label: '現地約定日検索',
            seq: 8,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '07',
            moduleId1: 'SbiForeignTradeDateSearch',
            serviceId: 'sbiSecBaseDateService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
        ],
      },
      {
        versionNo: -1,
        applicationId: 'MG02004000',
        parentApplicationId: 'MG02000000',
        applicationName: '取引制限管理',
        label: '取引制限管理',
        seq: 4,
        groupTypeFg: true,
        separaterTypeFg: false,
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
        children: [
          {
            versionNo: -1,
            applicationId: 'CW00500310',
            parentApplicationId: 'MG02004000',
            applicationName: '取引制限管理',
            label: '取引制限管理',
            seq: 1,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'TradeRestrictSearch',
            moduleId2: 'TradeRestrictForm',
            serviceId: 'tradeRestrictService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00500320',
            parentApplicationId: 'MG02004000',
            applicationName: '顧客取引制限管理',
            label: '顧客取引制限管理',
            seq: 2,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'AccountTradeRestrictSearch',
            moduleId2: 'AccountTradeRestrictForm',
            serviceId: 'accountTradeRestrictService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00500330',
            parentApplicationId: 'MG02004000',
            applicationName: '顧客グループ取引制限管理',
            label: '顧客グループ取引制限管理',
            seq: 3,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'GroupTradeRestrictSearch',
            moduleId2: 'GroupTradeRestrictForm',
            serviceId: 'groupTradeRestrictService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00500340',
            parentApplicationId: 'MG02004000',
            applicationName: '取引制限グループ登録',
            label: '取引制限グループ登録',
            seq: 4,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'TradeRestrictGroupSearch',
            moduleId2: 'TradeRestrictGroupForm',
            serviceId: 'tradeRestrictGroupService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00500350',
            parentApplicationId: 'MG02004000',
            applicationName: '取引制限グループ口座登録',
            label: '取引制限グループ口座登録',
            seq: 5,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '13',
            moduleId1: 'RestrictGroupMembersSearch',
            moduleId2: 'RestrictGroupMembersForm',
            serviceId: 'restrictGroupMembersService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
        ],
      },
      {
        versionNo: -1,
        applicationId: 'MG02005000',
        parentApplicationId: 'MG02000000',
        applicationName: 'その他の管理',
        label: 'その他の管理',
        seq: 5,
        groupTypeFg: true,
        separaterTypeFg: false,
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
        children: [
          {
            versionNo: -1,
            applicationId: 'CW00500130',
            parentApplicationId: 'MG02005000',
            applicationName: '自社決済銀行情報',
            label: '自社決済銀行情報',
            seq: 1,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'SelfBankInfoSearch',
            moduleId2: 'SelfBankInfoForm',
            serviceId: 'selfBankService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00500250',
            parentApplicationId: 'MG02005000',
            applicationName: '税率情報',
            label: '税率情報',
            seq: 4,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'GeneralTaxInfoSearch',
            moduleId2: 'GeneralTaxInfoForm',
            serviceId: 'generalTaxService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00500240',
            parentApplicationId: 'MG02005000',
            applicationName: '郵便番号ファイルアップロード',
            label: '郵便番号ファイルアップロード',
            seq: 5,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '07',
            moduleId1: 'PostalCodeUpload',
            serviceId: 'postalCodeUploadService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00900110',
            parentApplicationId: 'MG02005000',
            applicationName: '作業ステータス管理',
            label: '作業ステータス管理',
            seq: 6,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '08',
            moduleId1: 'OperationStatusSearch',
            moduleId2: 'OperationStatusForm',
            serviceId: 'userOperationService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00500410',
            parentApplicationId: 'MG02005000',
            applicationName: '利用者ログオン管理',
            label: '利用者ログオン管理',
            seq: 10,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '05',
            moduleId2: 'UserLogonState',
            serviceId: 'userLogonInfoService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
          },
        ],
      },
      {
        versionNo: -1,
        applicationId: 'MG02006000',
        parentApplicationId: 'MG02000000',
        applicationName: 'インターフェース管理',
        label: 'インターフェース管理',
        seq: 5,
        groupTypeFg: true,
        separaterTypeFg: false,
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20200101',
        applyEndDate: '99999999',
        children: [
          {
            versionNo: -1,
            applicationId: 'CW00900200',
            parentApplicationId: 'MG02006000',
            applicationName: 'BB-API呼出結果照会',
            label: 'BB-API呼出結果照会',
            seq: 1,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '10',
            moduleId1: 'SbiBbManagerList',
            serviceId: 'sbiBbManagerService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20200101',
            applyEndDate: '99999999',
          },
          {
            versionNo: -1,
            applicationId: 'CW00900201',
            parentApplicationId: 'MG02006000',
            applicationName: 'BB-API呼出結果詳細',
            label: 'BB-API呼出結果詳細',
            seq: 2,
            groupTypeFg: false,
            separaterTypeFg: false,
            templateTypeCode: '01',
            moduleId1: 'SbiBbManagerSearch',
            moduleId2: 'SbiBbManagerForm',
            serviceId: 'sbiBbManagerService',
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20200101',
            applyEndDate: '99999999',
          },
        ],
      },
    ],
  },
  {
    versionNo: -1,
    applicationId: 'MG01010004',
    parentApplicationId: '[ROOT]',
    applicationName: '市場取次管理',
    label: '市場取次管理',
    seq: 3,
    groupTypeFg: true,
    separaterTypeFg: false,
    authorityLevel: '2',
    menuFg: true,
    applyStartDate: '20000101',
    applyEndDate: '99999999',
    children: [
      {
        versionNo: -1,
        applicationId: 'CW00900320',
        parentApplicationId: 'MG01010004',
        applicationName: '市場取次送信データ管理',
        label: '市場取次送信データ管理',
        seq: 2,
        groupTypeFg: false,
        separaterTypeFg: false,
        templateTypeCode: '03',
        moduleId1: 'SendOrderList',
        serviceId: 'orderSendReceiveService',
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
      },
      {
        versionNo: -1,
        applicationId: 'CW00900330',
        parentApplicationId: 'MG01010004',
        applicationName: '市場取次受信データ管理',
        label: '市場取次受信データ管理',
        seq: 3,
        groupTypeFg: false,
        separaterTypeFg: false,
        templateTypeCode: '03',
        moduleId1: 'ReceiveOrderList',
        serviceId: 'orderSendReceiveService',
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
      },
      {
        versionNo: -1,
        applicationId: 'CW00900340',
        parentApplicationId: 'MG01010004',
        applicationName: '市場取次訂正取消番号管理',
        label: '市場取次訂正取消番号管理',
        seq: 4,
        groupTypeFg: false,
        separaterTypeFg: false,
        templateTypeCode: '09',
        moduleId1: 'ReceiveOrderFixSearch',
        moduleId2: 'ReceiveOrderFixForm',
        serviceId: 'orderSendReceiveService',
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
      },
      {
        versionNo: -1,
        applicationId: 'CW00900350',
        parentApplicationId: 'MG01010004',
        applicationName: 'リジェクト注文再送指示',
        label: 'リジェクト注文再送指示',
        seq: 5,
        groupTypeFg: false,
        separaterTypeFg: false,
        templateTypeCode: '10',
        moduleId1: 'ResendOrderList',
        serviceId: 'orderSendReceiveService',
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
      },
      {
        versionNo: -1,
        applicationId: 'CW00900360',
        parentApplicationId: 'MG01010004',
        applicationName: 'リジェクト注文失効反映指示',
        label: 'リジェクト注文失効反映指示',
        seq: 6,
        groupTypeFg: false,
        separaterTypeFg: false,
        templateTypeCode: '10',
        moduleId1: 'ReflectionOrderList',
        serviceId: 'orderSendReceiveService',
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
      },
      {
        versionNo: -1,
        applicationId: 'CW00900370',
        parentApplicationId: 'MG01010004',
        applicationName: 'リジェクト理由管理',
        label: 'リジェクト理由管理',
        seq: 7,
        groupTypeFg: false,
        separaterTypeFg: false,
        templateTypeCode: '01',
        moduleId1: 'OrderRejectMessageSearch',
        moduleId2: 'OrderRejectMessageForm',
        serviceId: 'orderSendReceiveService',
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
      },
    ],
  },
  {
    versionNo: -1,
    applicationId: 'MG03000000',
    parentApplicationId: '[ROOT]',
    applicationName: 'ログオン情報',
    label: 'ログオン情報',
    seq: 4,
    groupTypeFg: true,
    separaterTypeFg: false,
    authorityLevel: '2',
    menuFg: true,
    applyStartDate: '20000101',
    applyEndDate: '99999999',
    children: [
      {
        versionNo: -1,
        applicationId: 'CW00800020',
        parentApplicationId: 'MG03000000',
        applicationName: 'パスワード変更',
        label: 'パスワード変更',
        seq: 1,
        groupTypeFg: false,
        separaterTypeFg: false,
        templateTypeCode: '05',
        moduleId2: 'ModifyPassword',
        serviceId: 'usersService',
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
      },
      {
        versionNo: -1,
        applicationId: 'CW00800040',
        parentApplicationId: 'MG03000000',
        applicationName: 'ログオン履歴',
        label: 'ログオン履歴',
        seq: 2,
        groupTypeFg: false,
        separaterTypeFg: false,
        templateTypeCode: '04',
        moduleId1: 'UserLogonHistory',
        serviceId: 'userLogonInfoService',
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
      },
    ],
  },
  {
    versionNo: -1,
    applicationId: 'TWMENUSUB',
    parentApplicationId: '[ROOT]',
    applicationName: 'TWメンテナンス',
    label: 'TWメンテナンス',
    seq: 5,
    groupTypeFg: true,
    separaterTypeFg: false,
    authorityLevel: '2',
    menuFg: true,
    applyStartDate: '20000101',
    applyEndDate: '99999999',
    children: [
      {
        versionNo: -1,
        applicationId: 'CW00900030',
        parentApplicationId: 'TWMENUSUB',
        applicationName: '市場別カレンダー情報',
        label: '市場別カレンダー情報',
        seq: 3,
        groupTypeFg: false,
        separaterTypeFg: false,
        templateTypeCode: '06',
        moduleId1: 'CalendarSearch',
        moduleId2: 'CalendarForm',
        serviceId: 'calendarMarketService',
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
      },
      {
        versionNo: -1,
        applicationId: 'CW81510010',
        parentApplicationId: 'TWMENUSUB',
        applicationName: '現地手数料情報',
        label: '現地手数料情報',
        seq: 6,
        groupTypeFg: false,
        separaterTypeFg: false,
        templateTypeCode: '01',
        moduleId1: 'ForeignChargeInfoSearch',
        moduleId2: 'ForeignChargeInfoForm',
        serviceId: 'foreignChargeService',
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
      },
      {
        versionNo: -1,
        applicationId: 'CW00900051',
        parentApplicationId: 'TWMENUSUB',
        applicationName: 'カレンダー基本情報',
        label: 'カレンダー基本情報',
        seq: 7,
        groupTypeFg: false,
        separaterTypeFg: false,
        templateTypeCode: '15',
        moduleId1: 'CalendarInfoSearch',
        moduleId2: 'CalendarInfoForm',
        serviceId: 'calendarInfoService',
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
      },
      {
        versionNo: -1,
        applicationId: 'CW00010070',
        parentApplicationId: 'TWMENUSUB',
        applicationName: '顧客簿価補正',
        label: '顧客簿価補正',
        seq: 8,
        groupTypeFg: false,
        separaterTypeFg: false,
        templateTypeCode: '09',
        moduleId1: 'UpdateBookCostSearch',
        moduleId2: 'UpdateBookCostForm',
        serviceId: 'balanceService',
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
      },
    ],
  },
  {
    versionNo: -1,
    applicationId: 'MG06000000',
    parentApplicationId: '[ROOT]',
    applicationName: '仲介業務',
    label: '仲介業務',
    seq: 6,
    groupTypeFg: true,
    separaterTypeFg: false,
    authorityLevel: '2',
    menuFg: true,
    applyStartDate: '20000101',
    applyEndDate: '99999999',
    children: [
      {
        versionNo: -1,
        applicationId: 'MG06001000',
        parentApplicationId: 'MG06000000',
        applicationName: '取引（注文・約定）',
        label: '取引（注文・約定）',
        seq: 1,
        groupTypeFg: true,
        separaterTypeFg: false,
        authorityLevel: '2',
        menuFg: true,
        applyStartDate: '20000101',
        applyEndDate: '99999999',
        children: [
          {
            versionNo: -1,
            applicationId: 'MG06001003',
            parentApplicationId: 'MG06001000',
            applicationName: '外国債券',
            label: '外国債券',
            seq: 1,
            groupTypeFg: true,
            separaterTypeFg: false,
            authorityLevel: '2',
            menuFg: true,
            applyStartDate: '20000101',
            applyEndDate: '99999999',
            children: [
              {
                versionNo: -1,
                applicationId: 'CW8200005S',
                parentApplicationId: 'MG06001003',
                applicationName: '外国債券（新発募集）買付注文',
                label: '外国債券（新発募集）買付注文',
                seq: 1,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '05',
                moduleId2: 'SbiForeignBondBuyFromBrokerOrder',
                serviceId: 'sbiForeignBondOutsideOrderBrokerService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
              {
                versionNo: -1,
                applicationId: 'CW8200012S',
                parentApplicationId: 'MG06001003',
                applicationName: '外国債券注文一覧',
                label: '外国債券注文一覧',
                seq: 2,
                groupTypeFg: false,
                separaterTypeFg: false,
                templateTypeCode: '03',
                moduleId1: 'SbiForeignBondFromBrokerOrderList',
                serviceId: 'foreignBondOutsideOrderService',
                authorityLevel: '2',
                menuFg: true,
                applyStartDate: '20000101',
                applyEndDate: '99999999',
              },
            ],
          },
        ],
      },
    ],
  },
];
</script>

<template>
  <div class="flex h-screen flex-col">
    <header class="header">
      <div class="header-left">
        <v-list class="base-list flex h-full !p-0" height="100%">
          <template v-for="item in item2" :key="item.id">
            <menu-item is-base-menu class="h-full !min-h-full" :menu-item-info="item" />
          </template>
        </v-list>
      </div>
      <div class="header-right">xx</div>
    </header>

    <main class="main">
      <s-window class="ml-20 mt-20" />
    </main>
  </div>
</template>

<style lang="scss">
.header {
  box-shadow: 0 0 3px 4px #9a9a9b;
  background: linear-gradient(180deg, #fdfdfd, #e0e0e0);
  transition: 0.3s all ease;
  @apply z-10 flex h-[31px] px-[11px] py-[5px];

  &-left {
    @apply relative h-full rounded-[5px] border border-[#c7c7c7] border-t-[#fefefe] px-3 py-[0.5px];

    .base-list {
      & > .v-list-item:hover {
        @apply bg-white;
      }
    }
  }

  .v-list {
    @apply bg-transparent;

    &-item {
      padding-inline: 10.5px !important;
      @apply min-h-0 cursor-pointer text-cdark-2 hover:bg-[#b2e1ff];

      &__overlay {
        @apply hidden;
      }

      .v-ripple__container {
        @apply hidden;
      }

      &-title {
        @apply text-xs font-medium;
      }
    }
  }

  .v-menu {
    .v-list {
      box-shadow: 2px 2px 4px 0 #9a9a9b !important;
      border: 1px solid #b8bbbd;
      @apply rounded-[3px];

      &-item {
        padding-left: 22px !important;
      }
    }
  }
}

.main {
  background: linear-gradient(164deg, #ffffff 34%, #f3f3f3 58%, #9ebdd4 76%, #144371 96%);
  @apply min-h-0 flex-1;
}
</style>
